name: "config-test"

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  config-test:
    runs-on: ubuntu-latest
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
          
      - name: Setup minio
        run: |
            docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ACCESS_KEY=minioadmin" \
                     -e "MINIO_SECRET_KEY=minioadmin" \
                     -v /tmp/data:/data \
                     -v ~/.mc/:/root/.minio \
                     minio/minio server /data     
                     
      - name: Download juicefs 
        run: | 
          wget -q https://github.com/juicedata/juicefs/releases/download/v1.0.0-beta2/juicefs-1.0.0-beta2-linux-amd64.tar.gz
          tar -zxf juicefs-1.0.0-beta2-linux-amd64.tar.gz
          
      - name: Test
        run: |
          meta_url=redis://127.0.0.1/1
          mount_point=/tmp/sync-test/
          mc config host add minio http://127.0.0.1:9000 minioadmin minioadmin
          mc admin user add minio juicedata juicedata
          mc admin policy set minio consoleAdmin user=juicedata
          ./juicefs format --storage minio --bucket http://localhost:9000/jfs-test --access-key juicedata --secret-key juicedata $meta_url myjfs
          ./juicefs mount $meta_url $mount_point -d
          echo abc > $mount_point/abc.txt && echo "write success"
          mc admin user remove minio juicedata
          mc admin user add minio juicedata juicedata1
          mc admin policy set minio consoleAdmin user=juicedata
          ./juicefs config $meta --access-key juicedata --secret-key juicedata1
          echo abc > $mount_point/def.txt && echo "write success"
          cat $mount_point/abc.txt | grep abc && echo "read success"
          exit 1
          
      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1
