name: "minio-test"

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '!docs/**'
      - '!.github/**'
      - '.github/minio-test.yml'
  pull_request:
    branches: 
      - main
    paths:
      - '**'
      - '!docs/**'
      - '!.github/**'
      - '.github/minio-test.yml'
  schedule:
    - cron: '*/15 10 * * *'
  workflow_dispatch:
  
jobs:
  minio-test:
    runs-on: ubuntu-latest
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      - name: Setup minio
        run: |
          docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ACCESS_KEY=minioadmin" \
                     -e "MINIO_SECRET_KEY=minioadmin" \
                     -v /tmp/data:/data \
                     -v /tmp/config:/root/.minio \
                     minio/minio server /data
                     
      - name: Download juicefs 
        run: | 
          wget -q https://github.com/juicedata/juicefs/releases/download/v1.0.0-beta2/juicefs-1.0.0-beta2-linux-amd64.tar.gz
          tar -zxf juicefs-1.0.0-beta2-linux-amd64.tar.gz
          
      - name: Test Format
        run: |
          meta_url=redis://127.0.0.1/1
          mount_point=/tmp/sync-test/
          ./juicefs format --storage minio --bucket http://localhost:9000/jfs-test --access-key minioadmin --secret-key minioadmin $meta_url myjfs
          ./juicefs mount $meta_url $mount_point -d         
          
      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1
