name: "session-test"

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  session-test:
    runs-on: ubuntu-latest
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps: 
      - name: Checkout source code for sync test
        uses: actions/checkout@v2
        with:
          repository: juicedata/juicefs
          path: juicefs-source
          
      - name: Init 
        run: |
          sudo /etc/init.d/mysql start
          
      - name: Download
        run: | 
          wget -q https://github.com/juicedata/juicefs/releases/download/v1.0.0-beta3/juicefs-1.0.0-beta3-linux-amd64.tar.gz
          tar -zxf juicefs-1.0.0-beta3-linux-amd64.tar.gz
          wget -q https://dl.minio.io/client/mc/release/linux-amd64/mc
          chmod +x mc 
          sudo apt install md5deep
          
      - name: Test with mysql
        run: | 
          meta_url="mysql://root:root@(127.0.0.1)/test_gateway"
          db_name=$(basename $meta_url)
          volume=myjfs
          mp=/tmp/myjfs
          mysql -uroot -proot -e "drop database if exists $db_name; create database $db_name;" 
          ./juicefs format $meta_url $volume          
          ./juicefs mount -d $meta_url $mp
          sleep 300
          sudo /etc/init.d/mysql stop
          sleep 300
          sudo /etc/init.d/mysql start
          ./juicefs status $meta_url 
          mp2=./juicefs status $meta_url | grep MountPoint | awk -F: '{print $2}' | sed 's/"//g'
          test -z "$mp2" && echo "session info is empty"; exit 1
          
      - name: Test with redis
        run: | 
          meta_url="redis://localhost/1"
          volume=myjfs
          mp=/tmp/myjfs
          ./juicefs format $meta_url $volume          
          ./juicefs mount -d $meta_url $mp
          sleep 300
          container_id=$(docker ps -a | grep redis | awk '{print $1}')
          sudo killall -9 redis-server
          sleep 300
          sudo docker restart $container_id
          ./juicefs status $meta_url 
          mp2=./juicefs status $meta_url | grep MountPoint | awk -F: '{print $2}' | sed 's/"//g'
          test -z "$mp2" && echo "session info is empty"; exit 1
          
      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1
