name: "test_slack_notify"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/15 10 * * *'
  workflow_dispatch:
  
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test
        run: | 
          exit 1
          
      - name: Send Slack Notification
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: "C03990BCCES"
          slack-message: "@${{ github.actor}} CI Check ${{ job.status }} on ${{ github.event_name }}\n${{ github.event.pull_request.title || github.event.head_commit.message }} \nhttps://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          payload: | 
            {"attachments": [
                {
                "color":"#6f42c1",
                "footer":"<https://juicefs.com/>",
                "footer_icon":"https://s.juicefs.com/static/jfs/logo.svg",
                "ts":1502411430,
                "mrkdwn_in":["text"],
                "author_name":"${{ github.event.pull_request.user.login || github.event.sender.login || github.actor }}",
                "author_link":"${{ github.event.pull_request.user.html_url || github.event.sender.html_url}}",
                "author_icon":"${{ github.event.pull_request.user.avatar_url || github.event.sender.avatar_url }}",
                "title":"${{ github.event.pull_request.title || github.event.head_commit.message }}",
                "title_link":" ${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                "fallback":"${{ github.event.pull_request.title || github.event.head_commit.message }}",
                "text":"${{ github.event.pull_request.title || github.event.head_commit.message }}",
                "pretext":"@${{ github.actor}}: CI check ${{ job.status }} on ${{ github.event_name }}"},

              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}  
          
      - name: Setup upterm session
        # if: ${{ steps.slack.outcome == 'success' }}
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1    
       
         
