name: "test_slack_notify"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/6 6,7 * * *'
  workflow_dispatch:
  
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test
        id: test
        run: | 
          exit 1
      - name: Send Notification To Slack
        id: send_notification_to_slack
        uses: slackapi/slack-github-action@v1.18.0
        if: github.event_name == 'schedule' && steps.test.conclusion == 'failure'
        with:
          channel-id: C7JH03S68
          slack-message: "Ignore me, just a test msg, See: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          

         
