name: "test_slack_notify"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/15 10 * * *'
  workflow_dispatch:
  
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test
        run: | 
          exit 1
          
      - name: Send Slack Notification
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
          if: ${{ github.event_name == 'pull_request' }}
          slack-message: "@${{ github.actor}} CI Check ${{ job.status }} on ${{ github.event_name }}\n${{ github.event.pull_request.title }}\nhttps://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          if: ${{ github.event_name == 'push' }}
          slack-message: "@${{ github.actor}} CI Check ${{ job.status }} on ${{ github.event_name }}\n${{ github.event.head_commit.message }}\nhttps://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
          slack-message: "@${{ github.actor}} CI Check ${{ job.status }} on ${{ github.event_name }}\nhttps://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}  

      - name: Setup upterm session
        # if: ${{ steps.slack.outcome == 'success' }}
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1    
       
         
