name: test-workflow-dispatch

on:
  workflow_dispatch:

jobs:
  test-github-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
     
  test-self-hosted-runner1:
    runs-on: self-hosted, daily-build
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
  pjdfstest:
    runs-on: self-hosted, daily-build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build linux target
        run: make juicefs

      - name: Run Redis
        run: |
          sudo docker run -d --name redis -v redis-data:/data  \
          -p 6379:6379  redis redis-server --appendonly yes
      - name: Juicefs Format
        run: |
          sudo ./juicefs format redis://127.0.0.1:6379/1 --trash-days 0 pics
      - name: Juicefs Mount
        run: |
          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /tmp/jfs --no-usage-report &
      - name: Pjdfstest
        run: |
          sudo apt-get update
          sudo apt-get install -y libtap-harness-archive-perl
          cd /tmp/jfs/
          git clone https://github.com/sanwan/pjdfstest.git
          cd pjdfstest
          autoreconf -ifs
          ./configure
          make pjdfstest
          sudo prove -rv tests/
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
