name: "test_postgres"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/15 10 * * *'
  workflow_dispatch:
  
jobs:
  test_postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Connect to PostgreSQL
        run: |
          export PGPASSWORD="postgres"
          db_name=testdb
          psql -h localhost -U postgres  -c "\set AUTOCOMMIT on\ndrop database if exists $db_name; create database $db_name;" 

      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1
          
